include:
    - local: 'cicd/*.yaml'

stages:
    - build
    - test

build: 
    stage: build
    script:
      - echo "Building project..."
      - mkdir build
      - touch build/config.json
    artifacts:
      paths:
        - build/

test:
    stage: test
    script:
        - echo "Running tests..."
        - test -f "build/config.json"
